### ISSUE TITLE
Issues with GraphLib?

### ISSUE THREAD

**Issue by Neubulae** [TonimatasDEV/PacketFixer#28]
```
[02:41:38] [Server thread/WARN]: [CoreMinecraftNetUtil#lambda$getServerConnection$5] Disallowed server connection for class_3222['JingF'/144, l='ServerLevel[world]', x=-65.36, y=117.00, z=-187.08, removed=UNLOADED_WITH_PLAYER] because it's channel is not open!
[02:41:38] [Server thread/ERROR]: Error sending GraphWorld chunk packets. World: 'ServerLevel[world]'/minecraft:overworld, Chunk: [-4, -17]
java.lang.IllegalStateException: You can only send NetIdData '.graphlib.chunk_data' through a minecraft connection! (Was given null)
	at alexiil.mc.lib.net.NetIdBase.validateSendingSide(NetIdBase.java:264) ~[libnetworkstack-0.10.0-e165339157038757.jar:?]
	at alexiil.mc.lib.net.NetIdBase.validateSendingSide(NetIdBase.java:255) ~[libnetworkstack-0.10.0-e165339157038757.jar:?]
	at alexiil.mc.lib.net.NetIdData.send(NetIdData.java:55) ~[libnetworkstack-0.10.0-e165339157038757.jar:?]
	at com.kneelawk.graphlib.impl.net.GLNet.sendChunkDataPacket(GLNet.java:276) ~[graphlib-1.4.0+1.20-ef8cca81f2fce21.jar:?]
	at com.kneelawk.graphlib.impl.graph.ServerGraphWorldStorage.sendChunkDataPackets(ServerGraphWorldStorage.java:132) ~[graphlib-1.4.0+1.20-ef8cca81f2fce21.jar:?]
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.handler$foj000$graphlib$onSendChunkDataPackets(ThreadedAnvilChunkStorage.java:8534) ~[server-intermediary.jar:?]
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.sendChunkDataPackets(ThreadedAnvilChunkStorage.java:1342) ~[server-intermediary.jar:?]
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.mddff051$c2me-notickvd$lambda$onMakeChunkAccessible$0$14(ThreadedAnvilChunkStorage.java:14513) ~[server-intermediary.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor.java:156) ~[server-intermediary.jar:?]
	at net.minecraft.server.world.ServerChunkManager$MainThreadExecutor.executeTask(ServerChunkManager.java:564) ~[server-intermediary.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor.java:130) ~[server-intermediary.jar:?]
	at net.minecraft.server.world.ServerChunkManager$MainThreadExecutor.runTask(ServerChunkManager.java:573) ~[server-intermediary.jar:?]
	at net.minecraft.server.world.ServerChunkManager.executeQueuedTasks(ServerChunkManager.java:282) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.runOneTask(MinecraftServer.java:24824) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.runTask(MinecraftServer.java:758) ~[server-intermediary.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor.java:115) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.runTasksTillTickEnd(MinecraftServer.java:742) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$ceb000$carpet$modifiedRunLoop(MinecraftServer.java:26951) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:650) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[02:41:38] [Server thread/WARN]: [CoreMinecraftNetUtil#lambda$getServerConnection$5] Disallowed server connection for class_3222['JingF'/144, l='ServerLevel[world]', x=-65.36, y=117.00, z=-187.08, removed=UNLOADED_WITH_PLAYER] because it's channel is not open!
[02:41:38] [Server thread/ERROR]: Error sending GraphWorld chunk packets. World: 'ServerLevel[world]'/minecraft:overworld, Chunk: [-3, -17]
java.lang.IllegalStateException: You can only send NetIdData '.graphlib.chunk_data' through a minecraft connection! (Was given null)
	at alexiil.mc.lib.net.NetIdBase.validateSendingSide(NetIdBase.java:264) ~[libnetworkstack-0.10.0-e165339157038757.jar:?]
	at alexiil.mc.lib.net.NetIdBase.validateSendingSide(NetIdBase.java:255) ~[libnetworkstack-0.10.0-e165339157038757.jar:?]
	at alexiil.mc.lib.net.NetIdData.send(NetIdData.java:55) ~[libnetworkstack-0.10.0-e165339157038757.jar:?]
	at com.kneelawk.graphlib.impl.net.GLNet.sendChunkDataPacket(GLNet.java:276) ~[graphlib-1.4.0+1.20-ef8cca81f2fce21.jar:?]
	at com.kneelawk.graphlib.impl.graph.ServerGraphWorldStorage.sendChunkDataPackets(ServerGraphWorldStorage.java:132) ~[graphlib-1.4.0+1.20-ef8cca81f2fce21.jar:?]
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.handler$foj000$graphlib$onSendChunkDataPackets(ThreadedAnvilChunkStorage.java:8534) ~[server-intermediary.jar:?]
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.sendChunkDataPackets(ThreadedAnvilChunkStorage.java:1342) ~[server-intermediary.jar:?]
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.mddff051$c2me-notickvd$lambda$onMakeChunkAccessible$0$14(ThreadedAnvilChunkStorage.java:14513) ~[server-intermediary.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor.java:156) ~[server-intermediary.jar:?]
	at net.minecraft.server.world.ServerChunkManager$MainThreadExecutor.executeTask(ServerChunkManager.java:564) ~[server-intermediary.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor.java:130) ~[server-intermediary.jar:?]
	at net.minecraft.server.world.ServerChunkManager$MainThreadExecutor.runTask(ServerChunkManager.java:573) ~[server-intermediary.jar:?]
	at net.minecraft.server.world.ServerChunkManager.executeQueuedTasks(ServerChunkManager.java:282) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.runOneTask(MinecraftServer.java:24824) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.runTask(MinecraftServer.java:758) ~[server-intermediary.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor.java:115) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.runTasksTillTickEnd(MinecraftServer.java:742) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$ceb000$carpet$modifiedRunLoop(MinecraftServer.java:26951) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:650) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[02:41:38] [Server thread/WARN]: [CoreMinecraftNetUtil#lambda$getServerConnection$5] Disallowed server connection for class_3222['JingF'/144, l='ServerLevel[world]', x=-65.36, y=117.00, z=-187.08, removed=UNLOADED_WITH_PLAYER] because it's channel is not open!
[02:41:38] [Server thread/ERROR]: Error sending GraphWorld chunk packets. World: 'ServerLevel[world]'/minecraft:overworld, Chunk: [-2, -17]
java.lang.IllegalStateException: You can only send NetIdData '.graphlib.chunk_data' through a minecraft connection! (Was given null)
	at alexiil.mc.lib.net.NetIdBase.validateSendingSide(NetIdBase.java:264) ~[libnetworkstack-0.10.0-e165339157038757.jar:?]
	at alexiil.mc.lib.net.NetIdBase.validateSendingSide(NetIdBase.java:255) ~[libnetworkstack-0.10.0-e165339157038757.jar:?]
	at alexiil.mc.lib.net.NetIdData.send(NetIdData.java:55) ~[libnetworkstack-0.10.0-e165339157038757.jar:?]
	at com.kneelawk.graphlib.impl.net.GLNet.sendChunkDataPacket(GLNet.java:276) ~[graphlib-1.4.0+1.20-ef8cca81f2fce21.jar:?]
	at com.kneelawk.graphlib.impl.graph.ServerGraphWorldStorage.sendChunkDataPackets(ServerGraphWorldStorage.java:132) ~[graphlib-1.4.0+1.20-ef8cca81f2fce21.jar:?]
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.handler$foj000$graphlib$onSendChunkDataPackets(ThreadedAnvilChunkStorage.java:8534) ~[server-intermediary.jar:?]
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.sendChunkDataPackets(ThreadedAnvilChunkStorage.java:1342) ~[server-intermediary.jar:?]
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.mddff051$c2me-notickvd$lambda$onMakeChunkAccessible$0$14(ThreadedAnvilChunkStorage.java:14513) ~[server-intermediary.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor.java:156) ~[server-intermediary.jar:?]
	at net.minecraft.server.world.ServerChunkManager$MainThreadExecutor.executeTask(ServerChunkManager.java:564) ~[server-intermediary.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor.java:130) ~[server-intermediary.jar:?]
	at net.minecraft.server.world.ServerChunkManager$MainThreadExecutor.runTask(ServerChunkManager.java:573) ~[server-intermediary.jar:?]
	at net.minecraft.server.world.ServerChunkManager.executeQueuedTasks(ServerChunkManager.java:282) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.runOneTask(MinecraftServer.java:24824) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.runTask(MinecraftServer.java:758) ~[server-intermediary.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor.java:115) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.runTasksTillTickEnd(MinecraftServer.java:742) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$ceb000$carpet$modifiedRunLoop(MinecraftServer.java:26951) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:650) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]```

**Comment by TonimatasDEV** [comment]
I don't think this is caused by Packet Fixer

**Comment by Neubulae** [comment]
When I add PacketFixer to the game this happens.
Tho I am behind a Velocity proxy to be exact, I forgot to elaborate

**Comment by TonimatasDEV** [comment]
> When I add PacketFixer to the game this happens. Tho I am behind a Velocity proxy to be exact, I forgot to elaborate

Packet Fixer only delete the limit packet size.

**Comment by Neubulae** [comment]
O_O Okay, I suppose something other than this is wrong then
