### ISSUE TITLE
Receiving Payload may not be larger than 1048576 bytes in 1.20.1

### ISSUE THREAD

**Issue by mwheeler** [TonimatasDEV/PacketFixer#34]
Configuration:
- Minecraft 1.20.1
- Fabric Loader 0.15.10
- packetfixer 1.2.8

Issue:
- Client connects, but immediately crashes after joining with the classic "Payload may not be larger than 1048576 bytes".
- No issues or crash on server (player connects fine, then disconnects immediately from client crash).
- No issue creating a single player world either (modpack definitely crashes without PacketFixer in single player though!)

Modpack for reproduction if required: https://www.dropbox.com/scl/fo/87nzgnzbpqanyuc36s7pg/APimk4dwfnMFIBBAdswHXuo?rlkey=ap1lx5qdlz7odvn1dhelonu4b&st=66bi6r8n&dl=0

Attached copy/paste of the log section containing the stack trace:
[packet fixer crash.txt](https://github.com/TonimatasDEV/PacketFixer/files/15046110/packet.fixer.crash.txt)

Guessing something weird is going on with some origins or Create mod... unsure though / can't see an obvious culprit with my limited knowledge.

**Comment by TonimatasDEV** [comment]
> Configuration:
> 
> * Minecraft 1.20.1
> * Fabric Loader 0.15.10
> * packetfixer 1.2.8
> 
> Issue:
> 
> * Client connects, but immediately crashes after joining with the classic "Payload may not be larger than 1048576 bytes".
> * No issues or crash on server (player connects fine, then disconnects immediately from client crash).
> * No issue creating a single player world either (modpack definitely crashes without PacketFixer in single player though!)
> 
> Modpack for reproduction if required: https://www.dropbox.com/scl/fo/87nzgnzbpqanyuc36s7pg/APimk4dwfnMFIBBAdswHXuo?rlkey=ap1lx5qdlz7odvn1dhelonu4b&st=66bi6r8n&dl=0
> 
> Attached copy/paste of the log section containing the stack trace: [packet fixer crash.txt](https://github.com/TonimatasDEV/PacketFixer/files/15046110/packet.fixer.crash.txt)
> 
> Guessing something weird is going on with some origins or Create mod... unsure though / can't see an obvious culprit with my limited knowledge.

Have you the mod in both sides (client and server)?

**Comment by mwheeler** [comment]
I can confirm the configuration/mods are identical on both client+server (so yes).

With a bit of luck acting on a hunch... I can confirm this is origins++ (https://modrinth.com/mod/origins-plus-plus) causing issues that PacketFixer isn't handling when it sends some pretty hefty configs to the client.  Removing origins++ removes the problem.

I then stumbled upon others with this issue on their end: https://github.com/QuantumXenon/origins-plus-plus/issues/341

Their solution (to install XL packets: https://www.curseforge.com/minecraft/mc-mods/xl-packets-fabric) resolved my issue as well... so I'm not sure if you want to accept this as a "bug" (for PacketFixer to try and resolve without XL Packets) or close it as will-not-fix and just let people bring in XL packets to fix this issue.

Hopefully someone in the future finds this helpful.

**Comment by TonimatasDEV** [comment]
> fty configs to the client. Removing origins++ r

Delete XL packets and try this. Put this version in both sides
[PacketFixer-fabric-1.20.1-dev.zip](https://github.com/TonimatasDEV/PacketFixer/files/15047335/PacketFixer-fabric-1.20.1-dev.zip)

**Comment by mwheeler** [comment]
> > fty configs to the client. Removing origins++ r
> 
> Delete XL packets and try this. Put this version in both sides [PacketFixer-fabric-1.20.1-dev.zip](https://github.com/TonimatasDEV/PacketFixer/files/15047335/PacketFixer-fabric-1.20.1-dev.zip)

This doesn't load properly for me:
```
[18:30:50] [main/ERROR]: Mixin apply for mod packetfixer failed packetfixer-common.mixins.json:NbtAccounterMixin from mod packetfixer -> net.minecraft.class_2540: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @ModifyConstant annotation on newSize could not find any targets matching 'readNbt()Lnet/minecraft/nbt/CompoundTag;' in net.minecraft.class_2540. No refMap loaded. [PREINJECT Applicator Phase -> packetfixer-common.mixins.json:NbtAccounterMixin from mod packetfixer -> Prepare Injections ->  -> constant$dhi000$packetfixer$newSize(J)J -> Parse]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @ModifyConstant annotation on newSize could not find any targets matching 'readNbt()Lnet/minecraft/nbt/CompoundTag;' in net.minecraft.class_2540. No refMap loaded. [PREINJECT Applicator Phase -> packetfixer-common.mixins.json:NbtAccounterMixin from mod packetfixer -> Prepare Injections ->  -> constant$dhi000$packetfixer$newSize(J)J -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:658) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:589) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.ModifyConstantInjectionInfo.<init>(ModifyConstantInjectionInfo.java:54) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:710) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1329) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:422) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.10.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.<clinit>(RegistrySyncManager.java:67) ~[fabric-registry-sync-v0-2.3.3+1802ada577-bfed0ebc340fa6c1.jar:?]
	at net.minecraft.class_2370.onChange(class_2370.java:1177) ~[server-intermediary.jar:?]
	at net.minecraft.class_2370.handler$bob000$fabric-registry-sync-v0$set(class_2370.java:1172) ~[server-intermediary.jar:?]
	at net.minecraft.class_2370.method_46744(class_2370.java:181) ~[server-intermediary.jar:?]
	at net.minecraft.class_2370.method_10272(class_2370.java:186) ~[server-intermediary.jar:?]
	at net.minecraft.class_7923.method_47478(class_7923.java:217) ~[server-intermediary.jar:?]
	at net.minecraft.class_7923.method_47488(class_7923.java:209) ~[server-intermediary.jar:?]
	at net.minecraft.class_7923.method_47489(class_7923.java:197) ~[server-intermediary.jar:?]
	at net.minecraft.class_7923.<clinit>(class_7923.java:119) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:50) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:109) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.20.1-loader.0.15.10-launcher.1.0.1.jar:1.0.1]
[18:30:50] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:472) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.20.1-loader.0.15.10-launcher.1.0.1.jar:1.0.1]
Caused by: java.lang.ExceptionInInitializerError
	at net.minecraft.class_2370.onChange(class_2370.java:1177) ~[server-intermediary.jar:?]
	at net.minecraft.class_2370.handler$bob000$fabric-registry-sync-v0$set(class_2370.java:1172) ~[server-intermediary.jar:?]
	at net.minecraft.class_2370.method_46744(class_2370.java:181) ~[server-intermediary.jar:?]
	at net.minecraft.class_2370.method_10272(class_2370.java:186) ~[server-intermediary.jar:?]
	at net.minecraft.class_7923.method_47478(class_7923.java:217) ~[server-intermediary.jar:?]
	at net.minecraft.class_7923.method_47488(class_7923.java:209) ~[server-intermediary.jar:?]
	at net.minecraft.class_7923.method_47489(class_7923.java:197) ~[server-intermediary.jar:?]
	at net.minecraft.class_7923.<clinit>(class_7923.java:119) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:50) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:109) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.10.jar:?]
	... 4 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_2540 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.10.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.<clinit>(RegistrySyncManager.java:67) ~[fabric-registry-sync-v0-2.3.3+1802ada577-bfed0ebc340fa6c1.jar:?]
	at net.minecraft.class_2370.onChange(class_2370.java:1177) ~[server-intermediary.jar:?]
	at net.minecraft.class_2370.handler$bob000$fabric-registry-sync-v0$set(class_2370.java:1172) ~[server-intermediary.jar:?]
	at net.minecraft.class_2370.method_46744(class_2370.java:181) ~[server-intermediary.jar:?]
	at net.minecraft.class_2370.method_10272(class_2370.java:186) ~[server-intermediary.jar:?]
	at net.minecraft.class_7923.method_47478(class_7923.java:217) ~[server-intermediary.jar:?]
	at net.minecraft.class_7923.method_47488(class_7923.java:209) ~[server-intermediary.jar:?]
	at net.minecraft.class_7923.method_47489(class_7923.java:197) ~[server-intermediary.jar:?]
	at net.minecraft.class_7923.<clinit>(class_7923.java:119) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:50) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:109) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.10.jar:?]
	... 4 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.10.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.<clinit>(RegistrySyncManager.java:67) ~[fabric-registry-sync-v0-2.3.3+1802ada577-bfed0ebc340fa6c1.jar:?]
	at net.minecraft.class_2370.onChange(class_2370.java:1177) ~[server-intermediary.jar:?]
	at net.minecraft.class_2370.handler$bob000$fabric-registry-sync-v0$set(class_2370.java:1172) ~[server-intermediary.jar:?]
	at net.minecraft.class_2370.method_46744(class_2370.java:181) ~[server-intermediary.jar:?]
	at net.minecraft.class_2370.method_10272(class_2370.java:186) ~[server-intermediary.jar:?]
	at net.minecraft.class_7923.method_47478(class_7923.java:217) ~[server-intermediary.jar:?]
	at net.minecraft.class_7923.method_47488(class_7923.java:209) ~[server-intermediary.jar:?]
	at net.minecraft.class_7923.method_47489(class_7923.java:197) ~[server-intermediary.jar:?]
	at net.minecraft.class_7923.<clinit>(class_7923.java:119) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:50) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:109) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.10.jar:?]
	... 4 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [packetfixer-common.mixins.json:NbtAccounterMixin from mod packetfixer] from phase [DEFAULT] in config [packetfixer-common.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.10.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.<clinit>(RegistrySyncManager.java:67) ~[fabric-registry-sync-v0-2.3.3+1802ada577-bfed0ebc340fa6c1.jar:?]
	at net.minecraft.class_2370.onChange(class_2370.java:1177) ~[server-intermediary.jar:?]
	at net.minecraft.class_2370.handler$bob000$fabric-registry-sync-v0$set(class_2370.java:1172) ~[server-intermediary.jar:?]
	at net.minecraft.class_2370.method_46744(class_2370.java:181) ~[server-intermediary.jar:?]
	at net.minecraft.class_2370.method_10272(class_2370.java:186) ~[server-intermediary.jar:?]
	at net.minecraft.class_7923.method_47478(class_7923.java:217) ~[server-intermediary.jar:?]
	at net.minecraft.class_7923.method_47488(class_7923.java:209) ~[server-intermediary.jar:?]
	at net.minecraft.class_7923.method_47489(class_7923.java:197) ~[server-intermediary.jar:?]
	at net.minecraft.class_7923.<clinit>(class_7923.java:119) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:50) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:109) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.10.jar:?]
	... 4 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @ModifyConstant annotation on newSize could not find any targets matching 'readNbt()Lnet/minecraft/nbt/CompoundTag;' in net.minecraft.class_2540. No refMap loaded. [PREINJECT Applicator Phase -> packetfixer-common.mixins.json:NbtAccounterMixin from mod packetfixer -> Prepare Injections ->  -> constant$dhi000$packetfixer$newSize(J)J -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:658) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:589) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.ModifyConstantInjectionInfo.<init>(ModifyConstantInjectionInfo.java:54) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:710) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1329) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:422) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.10.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.<clinit>(RegistrySyncManager.java:67) ~[fabric-registry-sync-v0-2.3.3+1802ada577-bfed0ebc340fa6c1.jar:?]
	at net.minecraft.class_2370.onChange(class_2370.java:1177) ~[server-intermediary.jar:?]
	at net.minecraft.class_2370.handler$bob000$fabric-registry-sync-v0$set(class_2370.java:1172) ~[server-intermediary.jar:?]
	at net.minecraft.class_2370.method_46744(class_2370.java:181) ~[server-intermediary.jar:?]
	at net.minecraft.class_2370.method_10272(class_2370.java:186) ~[server-intermediary.jar:?]
	at net.minecraft.class_7923.method_47478(class_7923.java:217) ~[server-intermediary.jar:?]
	at net.minecraft.class_7923.method_47488(class_7923.java:209) ~[server-intermediary.jar:?]
	at net.minecraft.class_7923.method_47489(class_7923.java:197) ~[server-intermediary.jar:?]
	at net.minecraft.class_7923.<clinit>(class_7923.java:119) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:50) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:109) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.10.jar:?]
	... 4 more

```

**Comment by TonimatasDEV** [comment]
So sorry. Wrong version
[packetfixer-fabric-1.3.0-1.19-to-1.20.1.zip](https://github.com/TonimatasDEV/PacketFixer/files/15047564/packetfixer-fabric-1.3.0-1.19-to-1.20.1.zip)

**Comment by TonimatasDEV** [comment]
@mwheeler Sorry, worng version. Test it (I test it and works fine)
[packetfixer-fabric-1.3.0-1.19-to-1.20.1.zip](https://github.com/TonimatasDEV/PacketFixer/files/15047642/packetfixer-fabric-1.3.0-1.19-to-1.20.1.zip)

**Comment by mwheeler** [comment]
> @mwheeler Sorry, worng version. Test it (I test it and works fine) [packetfixer-fabric-1.3.0-1.19-to-1.20.1.zip](https://github.com/TonimatasDEV/PacketFixer/files/15047642/packetfixer-fabric-1.3.0-1.19-to-1.20.1.zip)

Can confirm this works perfectly! :) no more XL packets needed / bug fixed!
