### ISSUE TITLE
This new version was compiled with a class file version 65

### ISSUE THREAD

**Issue by tacogerbil** [TonimatasDEV/PacketFixer#42]
Nothing in the modrinth changelog and it causes a rash (with no crash log) during boot.
Log
[07:48:17] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.UnsupportedClassVersionError: net/minecraft/class_2540 has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 61.0
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:472) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.11.jar:?]
Caused by: java.lang.UnsupportedClassVersionError: net/minecraft/class_2540 has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 61.0
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.11.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.<clinit>(RegistrySyncManager.java:67) ~[fabric-registry-sync-v0-2.3.3+1802ada577-70a9685310656ab1.jar:?]
	at net.minecraft.class_2370.onChange(class_2370.java:677) ~[client-intermediary.jar:?]
	at net.minecraft.class_2370.handler$dak000$fabric-registry-sync-v0$set(class_2370.java:672) ~[client-intermediary.jar:?]
	at net.minecraft.class_2370.method_46744(class_2370.java:181) ~[client-intermediary.jar:?]
	at net.minecraft.class_2370.method_10272(class_2370.java:186) ~[client-intermediary.jar:?]
	at net.minecraft.class_7923.method_47478(class_7923.java:217) ~[client-intermediary.jar:?]
	at net.minecraft.class_7923.method_47488(class_7923.java:209) ~[client-intermediary.jar:?]
	at net.minecraft.class_7923.method_47489(class_7923.java:197) ~[client-intermediary.jar:?]
	at net.minecraft.class_7923.<clinit>(class_7923.java:119) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:50) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:166) ~[1.20.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	... 2 more
Process ended with code: 1

**Comment by TonimatasDEV** [comment]
> Nothing in the modrinth changelog and it causes a rash (with no crash log) during boot. Log [07:48:17] [main/ERROR]: Minecraft has crashed! net.fabricmc.loader.impl.FormattedException: java.lang.UnsupportedClassVersionError: net/minecraft/class_2540 has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 61.0 at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.15.11.jar:?] at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:472) ~[fabric-loader-0.15.11.jar:?] at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.11.jar:?] at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.11.jar:?] Caused by: java.lang.UnsupportedClassVersionError: net/minecraft/class_2540 has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 61.0 at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?] at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?] at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?] at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160) ~[fabric-loader-0.15.11.jar:?] at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.15.11.jar:?] at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.11.jar:?] at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.11.jar:?] at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] at net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.(RegistrySyncManager.java:67) ~[fabric-registry-sync-v0-2.3.3+1802ada577-70a9685310656ab1.jar:?] at net.minecraft.class_2370.onChange(class_2370.java:677) ~[client-intermediary.jar:?] at net.minecraft.class_2370.handler$dak000$fabric-registry-sync-v0$set(class_2370.java:672) ~[client-intermediary.jar:?] at net.minecraft.class_2370.method_46744(class_2370.java:181) ~[client-intermediary.jar:?] at net.minecraft.class_2370.method_10272(class_2370.java:186) ~[client-intermediary.jar:?] at net.minecraft.class_7923.method_47478(class_7923.java:217) ~[client-intermediary.jar:?] at net.minecraft.class_7923.method_47488(class_7923.java:209) ~[client-intermediary.jar:?] at net.minecraft.class_7923.method_47489(class_7923.java:197) ~[client-intermediary.jar:?] at net.minecraft.class_7923.(class_7923.java:119) ~[client-intermediary.jar:?] at net.minecraft.class_2966.method_12851(class_2966.java:50) ~[client-intermediary.jar:?] at net.minecraft.client.main.Main.main(Main.java:166) ~[1.20.1.jar:?] at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?] ... 2 more Process ended with code: 1

What version of minecraft are you using?

**Comment by TonimatasDEV** [comment]
Can't reproduce

**Comment by tacogerbil** [comment]
Are you using Java 17?  I'm on Java 17.
I also used javap -v PacketFixer.class .. I got **major version: 65** (from inside your jar file).  My understanding is that Major 65 is Java 21?

**Comment by tacogerbil** [comment]
> Can't reproduce

Are you using Java 17?  I'm on Java 17.
I also used javap -v PacketFixer.class .. I got **major version: 65** (from inside your jar file).  My understanding is that Major 65 is Java 21?
