### ISSUE TITLE
1.12.2 not working on server correctly for me

### ISSUE THREAD

**Issue by NordicGamerFE** [TonimatasDEV/PacketFixer#48]
server starts perfectly fine but i get the error below

`[21:06:41] [Netty Epoll Server IO #1/FATAL] [mixin]: Mixin apply for mod PacketFixer-forge-1.0.0-1.12.2.jar failed packetfixer.mixins.json:CPacketCustomPayloadMixin from mod PacketFixer-forge-1.0.0-1.12.2.jar -> net.minecraft.network.play.client.CPacketCustomPayload: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @ModifyConstant annotation on newSize$init could not find any targets matching 'Lnet/minecraft/network/play/client/CPacketCustomPayload;<init>(Ljava/lang/String;Lnet/minecraft/network/PacketBuffer;)V' in net.minecraft.network.play.client.CPacketCustomPayload. Using refmap packetfixer.mixins.refmap.json [PREINJECT Applicator Phase -> packetfixer.mixins.json:CPacketCustomPayloadMixin from mod PacketFixer-forge-1.0.0-1.12.2.jar -> Prepare Injections ->  -> constant$zmi000$packetfixer$newSize$init(I)I -> Parse]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @ModifyConstant annotation on newSize$init could not find any targets matching 'Lnet/minecraft/network/play/client/CPacketCustomPayload;<init>(Ljava/lang/String;Lnet/minecraft/network/PacketBuffer;)V' in net.minecraft.network.play.client.CPacketCustomPayload. Using refmap packetfixer.mixins.refmap.json [PREINJECT Applicator Phase -> packetfixer.mixins.json:CPacketCustomPayloadMixin from mod PacketFixer-forge-1.0.0-1.12.2.jar -> Prepare Injections ->  -> constant$zmi000$packetfixer$newSize$init(I)I -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656) ~[!mixinbooter-9.4.jar:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587) ~[!mixinbooter-9.4.jar:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330) ~[!mixinbooter-9.4.jar:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316) ~[!mixinbooter-9.4.jar:?]
	at org.spongepowered.asm.mixin.injection.struct.ModifyConstantInjectionInfo.<init>(ModifyConstantInjectionInfo.java:54) ~[!mixinbooter-9.4.jar:?]
	at sun.reflect.GeneratedConstructorAccessor60.newInstance(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_312]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_312]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149) ~[!mixinbooter-9.4.jar:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708) ~[!mixinbooter-9.4.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1329) ~[!mixinbooter-9.4.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053) ~[!mixinbooter-9.4.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395) ~[!mixinbooter-9.4.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[!mixinbooter-9.4.jar:?]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[!mixinbooter-9.4.jar:?]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[!mixinbooter-9.4.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:377) [!mixinbooter-9.4.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:240) [!mixinbooter-9.4.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:208) [!mixinbooter-9.4.jar:?]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:71) [!mixinbooter-9.4.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) [?:1.8.0_312]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) [?:1.8.0_312]
	at net.minecraft.network.EnumConnectionState$2.<init>(SourceFile:226) [gx$2.class:?]
	at net.minecraft.network.EnumConnectionState.<clinit>(SourceFile:135) [gx.class:?]
	at net.minecraft.network.NetworkManager.channelActive(NetworkManager.java:104) [gw.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213) [AbstractChannelHandlerContext.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199) [AbstractChannelHandlerContext.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:192) [AbstractChannelHandlerContext.class:?]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:64) [ChannelInboundHandlerAdapter.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213) [AbstractChannelHandlerContext.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199) [AbstractChannelHandlerContext.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:192) [AbstractChannelHandlerContext.class:?]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:64) [ChannelInboundHandlerAdapter.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213) [AbstractChannelHandlerContext.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199) [AbstractChannelHandlerContext.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:192) [AbstractChannelHandlerContext.class:?]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:64) [ChannelInboundHandlerAdapter.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213) [AbstractChannelHandlerContext.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199) [AbstractChannelHandlerContext.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:192) [AbstractChannelHandlerContext.class:?]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:64) [ChannelInboundHandlerAdapter.class:?]
	at io.netty.handler.timeout.IdleStateHandler.channelActive(IdleStateHandler.java:272) [IdleStateHandler.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213) [AbstractChannelHandlerContext.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199) [AbstractChannelHandlerContext.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:192) [AbstractChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelActive(DefaultChannelPipeline.java:1322) [DefaultChannelPipeline$HeadContext.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213) [AbstractChannelHandlerContext.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199) [AbstractChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelActive(DefaultChannelPipeline.java:902) [DefaultChannelPipeline.class:?]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:514) [AbstractChannel$AbstractUnsafe.class:?]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:419) [AbstractChannel$AbstractUnsafe.class:?]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:478) [AbstractChannel$AbstractUnsafe$1.class:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [AbstractEventExecutor.class:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) [SingleThreadEventExecutor.class:?]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304) [EpollEventLoop.class:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [SingleThreadEventExecutor$5.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
[21:06:41] [Netty Epoll Server IO #1/FATAL] [net.minecraft.network.NetworkManager]: java.lang.NoClassDefFoundError: net/minecraft/network/play/client/CPacketCustomPayload
[21:06:41] [Netty Epoll Server IO #2/FATAL] [net.minecraft.network.NetworkManager]: java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.network.EnumConnectionState`

I cannot join the server and when i try to do so i get the error
`[21:57:10] [Netty Epoll Server IO #21/FATAL] [minecraft/NetworkManager]: java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.network.EnumConnectionState`

**Comment by TonimatasDEV** [comment]
@NordicGamerFE I need the modlist

**Comment by NordicGamerFE** [comment]
Ocean Outlast version 79A

**Comment by TonimatasDEV** [comment]
@NordicGamerFE Fixed in the latest version (1.0.2): https://modrinth.com/mod/packet-fixer
